default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # - id: no-commit-to-branch
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: check-commit-msg
        name: check commit message
        language: pygrep
        entry: "^(feat|fix|docs|test|refactor|build|perf|format): .*$"
        args: [--negate, --multiline]
        stages: [commit-msg]
        always_run: true
