"""init

Revision ID: 03ec25e6a304
Revises:
Create Date: 2026-06-29 13:39:30.858852

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03ec25e6a304"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_roles",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "ONGOING",
                "COMPLETED",
                "STOPPED",
                "DISCARDED",
                name="statustype",
            ),
            server_default="NOT_STARTED",
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skills",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("STACK", "TECHNICAL", "NON_TECHNICAL", name="skilltype"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_roles",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "employees",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("experience", sa.Integer(), nullable=False),
        sa.Column("date_of_joining", sa.Date(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("system_role_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["system_role_id"],
            ["system_roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_logs",
        sa.Column(
            "entity_name",
            sa.Enum(
                "EMPLOYEE",
                "PROJECT",
                "PROJECT_EMPLOYEE",
                "PROJECT_REQUIREMENT",
                "PROJECT_REQUIREMENT_REQUEST",
                "FEEDBACK",
                "EMPLOYEE_SKILL",
                name="entityname",
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("CREATE", "UPDATE", "DELETE", name="actiontype"),
            nullable=False,
        ),
        sa.Column("field_name", sa.Text(), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("changed_by_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["changed_by_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_changed_by_id"),
        "audit_logs",
        ["changed_by_id"],
        unique=False,
    )
    op.create_table(
        "employee_skills",
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("proficiency", sa.Integer(), nullable=False),
        sa.Column(
            "is_interest", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("proficiency BETWEEN 0 AND 5", name="ck_proficiency_range"),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "skill_id", name="uq_employee_stack"),
    )
    op.create_index(
        op.f("ix_employee_skills_employee_id"),
        "employee_skills",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_skills_skill_id"),
        "employee_skills",
        ["skill_id"],
        unique=False,
    )
    op.create_table(
        "feedbacks",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "feedback_type",
            sa.Enum("GENERAL", "PERFORMANCE", "ISSUE", name="feedbacktype"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feedbacks_created_by"), "feedbacks", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_feedbacks_project_id"), "feedbacks", ["project_id"], unique=False
    )
    op.create_table(
        "project_requirement_requests",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("project_role_id", sa.Integer(), nullable=False),
        sa.Column("requested_count", sa.Integer(), nullable=False),
        sa.Column("requested_by", sa.Integer(), nullable=False),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="requeststatus"),
            nullable=False,
        ),
        sa.Column("fulfilled_requirement_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("requested_count > 0", name="ck_requested_count_positive"),
        sa.ForeignKeyConstraint(
            ["fulfilled_requirement_id"],
            ["project_requirement_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_role_id"],
            ["project_roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_requirement_requests_fulfilled_requirement_id"),
        "project_requirement_requests",
        ["fulfilled_requirement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_requirement_requests_project_id"),
        "project_requirement_requests",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_requirement_requests_project_role_id"),
        "project_requirement_requests",
        ["project_role_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_requirement_requests_requested_by"),
        "project_requirement_requests",
        ["requested_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_requirement_requests_resolved_by"),
        "project_requirement_requests",
        ["resolved_by"],
        unique=False,
    )
    op.create_table(
        "project_employees",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("project_role_id", sa.Integer(), nullable=False),
        sa.Column(
            "is_shadow", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("date_assigned", sa.Date(), nullable=False),
        sa.Column("date_exited", sa.Date(), nullable=True),
        sa.Column("requirement_request_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "date_exited IS NULL OR date_exited >= date_assigned",
            name="ck_exit_after_assign",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_role_id"],
            ["project_roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requirement_request_id"],
            ["project_requirement_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_employees_employee_id"),
        "project_employees",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_employees_project_id"),
        "project_employees",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_employees_project_role_id"),
        "project_employees",
        ["project_role_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_employees_requirement_request_id"),
        "project_employees",
        ["requirement_request_id"],
        unique=False,
    )
    op.create_table(
        "project_stack_requirement_requests",
        sa.Column("project_requirement_request_id", sa.Integer(), nullable=False),
        sa.Column("stack_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_requirement_request_id"],
            ["project_requirement_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stack_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_requirement_request_id", "stack_id", name="uq_request_stack"
        ),
    )
    op.create_index(
        op.f("ix_project_stack_requirement_requests_project_requirement_request_id"),
        "project_stack_requirement_requests",
        ["project_requirement_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_stack_requirement_requests_stack_id"),
        "project_stack_requirement_requests",
        ["stack_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_stack_requirement_requests_stack_id"),
        table_name="project_stack_requirement_requests",
    )
    op.drop_index(
        op.f("ix_project_stack_requirement_requests_project_requirement_request_id"),
        table_name="project_stack_requirement_requests",
    )
    op.drop_table("project_stack_requirement_requests")
    op.drop_index(
        op.f("ix_project_employees_requirement_request_id"),
        table_name="project_employees",
    )
    op.drop_index(
        op.f("ix_project_employees_project_role_id"), table_name="project_employees"
    )
    op.drop_index(
        op.f("ix_project_employees_project_id"), table_name="project_employees"
    )
    op.drop_index(
        op.f("ix_project_employees_employee_id"), table_name="project_employees"
    )
    op.drop_table("project_employees")
    op.drop_index(
        op.f("ix_project_requirement_requests_resolved_by"),
        table_name="project_requirement_requests",
    )
    op.drop_index(
        op.f("ix_project_requirement_requests_requested_by"),
        table_name="project_requirement_requests",
    )
    op.drop_index(
        op.f("ix_project_requirement_requests_project_role_id"),
        table_name="project_requirement_requests",
    )
    op.drop_index(
        op.f("ix_project_requirement_requests_project_id"),
        table_name="project_requirement_requests",
    )
    op.drop_index(
        op.f("ix_project_requirement_requests_fulfilled_requirement_id"),
        table_name="project_requirement_requests",
    )
    op.drop_table("project_requirement_requests")
    op.drop_index(op.f("ix_feedbacks_project_id"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_created_by"), table_name="feedbacks")
    op.drop_table("feedbacks")
    op.drop_index(op.f("ix_employee_skills_skill_id"), table_name="employee_skills")
    op.drop_index(op.f("ix_employee_skills_employee_id"), table_name="employee_skills")
    op.drop_table("employee_skills")
    op.drop_index(op.f("ix_audit_logs_changed_by_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("employees")
    op.drop_table("system_roles")
    op.drop_table("skills")
    op.drop_table("projects")
    op.drop_table("project_roles")
    # ### end Alembic commands ###
