"""fix: add end_date to employee

Revision ID: 05e586e8ee27
Revises: 07999595a75b
Create Date: 2026-07-01 12:56:05.146226

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05e586e8ee27"
down_revision: Union[str, Sequence[str], None] = "07999595a75b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employees", sa.Column("end_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "end_date")
    # ### end Alembic commands ###
