"""add start_date to project_employee

Revision ID: 07999595a75b
Revises: 792fefe940f9
Create Date: 2026-07-01 10:02:36.182603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07999595a75b'
down_revision: Union[str, Sequence[str], None] = '792fefe940f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_employees', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_employees', 'start_date')
    # ### end Alembic commands ###
