"""feat: add project x stacks

Revision ID: 480268458e7a
Revises: d45472c7f1ac
Create Date: 2026-06-30 13:45:01.286207

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "480268458e7a"
down_revision: Union[str, Sequence[str], None] = "d45472c7f1ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_stacks",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_stacks_project_id"),
        "project_stacks",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_stacks_skill_id"), "project_stacks", ["skill_id"], unique=False
    )
    op.create_index(
        "uq_project_skill_active",
        "project_stacks",
        ["project_id", "skill_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_project_skill_active",
        table_name="project_stacks",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_project_stacks_skill_id"), table_name="project_stacks")
    op.drop_index(op.f("ix_project_stacks_project_id"), table_name="project_stacks")
    op.drop_table("project_stacks")
    # ### end Alembic commands ###
