"""fix: change nullable to True for duration and start date in Project Model

Revision ID: 792fefe940f9
Revises: 480268458e7a
Create Date: 2026-06-30 14:04:15.667137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "792fefe940f9"
down_revision: Union[str, Sequence[str], None] = "480268458e7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "start_date", existing_type=sa.DATE(), nullable=True)
    op.alter_column("projects", "duration", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "duration", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("projects", "start_date", existing_type=sa.DATE(), nullable=False)
    # ### end Alembic commands ###
