"""remove redundant employee stacks relationship mapping

Revision ID: d45472c7f1ac
Revises: 177e7fade9f8
Create Date: 2026-06-30 07:08:43.646300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45472c7f1ac'
down_revision: Union[str, Sequence[str], None] = '177e7fade9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
