"""add assigned_count col to reqrequest

Revision ID: d6032f49d419
Revises: 05e586e8ee27
Create Date: 2026-07-01 13:32:29.653091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6032f49d419'
down_revision: Union[str, Sequence[str], None] = '05e586e8ee27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_requirement_requests', sa.Column('assigned_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_requirement_requests', 'assigned_count')
    # ### end Alembic commands ###
